"""Added publiclobby to LauncherSettings

Revision ID: 3103e5ae5314
Revises: ae1eab510d76
Create Date: 2024-02-27 07:56:10.609453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3103e5ae5314'
down_revision = 'ae1eab510d76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('launcher_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publiclobby', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('launcher_settings', schema=None) as batch_op:
        batch_op.drop_column('publiclobby')

    # ### end Alembic commands ###
