"""Added Players Table, Added SteamAuth and EnforceSteamAuthIP Launcher settings

Revision ID: 59a004fd30a9
Revises: 170971d44a48
Create Date: 2024-03-14 10:59:09.018069

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "59a004fd30a9"
down_revision = "170971d44a48"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("launcher_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("steam_auth", sa.Boolean(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("enforce_steam_auth_ip", sa.Boolean(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("launcher_settings", schema=None) as batch_op:
        batch_op.drop_column("enforce_steam_auth_ip")
        batch_op.drop_column("steam_auth")

    # ### end Alembic commands ###
